### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
This was intended to fix an encoding issue but it appears to be an issue with the gcloud module.
I made a PR, https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1947, and we should merge this when that fix lands (I will update this PR when that fix lands).

**Comment by idoshamun** [comment]
Great!
Waiting for your update, thanks for contributing

**Comment by AdriVanHoudt** [comment]
@idoshamun ready to go :D :shipit:

**Comment by idoshamun** [comment]
Published in v0.1.4

**Comment by AdriVanHoudt** [comment]
Thanks!

**Pull request merged**
