### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
This could potentially solve a mem leak see https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2135

**Comment by idoshamun** [comment]
@AdriVanHoudt thanks for the PR!
I'll take a look into it soon, need to fix travis config (#3) as well

**Comment by AdriVanHoudt** [comment]
@idoshamun cool would be awesome!

**Comment by idoshamun** [comment]
So after a very deep research, I found out that when submitting a PR from a fork, travis disables secured env vars and files, this is why the build always fails. So I'll approve this one without passing the build

**Comment by idoshamun** [comment]
Released in 0.1.5

**Comment by AdriVanHoudt** [comment]
Awesome 🎉 and that kinda sucks to test PR's then :/

**Comment by idoshamun** [comment]
Totally agree, have to think about some other way

**Pull request merged**
